Repository Dev-FE-2/toy-project2-team3, pull requests merged in 2024-12, with the labels that each got.

#9 [Setting] 파이어베이스 기초 설정을 프로젝트에 포함시킵니다
  .gitignore
  package-lock.json
  package.json
  src/firebase/.gitkeep
  src/firebaseConfig.ts
Labels: ⚙ Setting

#12 [Settings] CommitLint, ESLint, PrettierLint 설치
  .commitlintrc.json
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc
  package-lock.json
  package.json
Labels: ⚙ Settings

#17 [Feature] DB 구조를 기반으로 interface 타입을 정의합니다
  src/types/interface.ts
Labels: ✨ Feature

#21 [Design] 사용자가 업무를 확인할 수 있도록 보여지는 메인 캘린더 UI를 구현합니다. #11
  package-lock.json
  package.json
  src/App.css
  src/index.css
  src/pages/user/Schedule/ScheduleHeader/MonthPicker/index.tsx
  src/pages/user/Schedule/ScheduleHeader/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendar/MainCalendarDays/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendar/index.tsx
  src/pages/user/Schedule/ScheduleMain/index.tsx
  src/pages/user/Schedule/ScheduleSideBar/index.tsx
  src/pages/user/Schedule/core/TeamList/index.tsx
  src/pages/user/Schedule/index.tsx
  src/types/interface.ts
Labels: 🎨 Html&css

#31 [Settings] Redux Toolkit 설치 및 셋팅합니다
  package-lock.json
  package.json
  src/App.tsx
  src/components/Counter.tsx
  src/components/Layout/index.tsx
  src/main.tsx
  src/routes/Router.tsx
  src/slices/counter/actions.ts
  src/slices/counter/counterSlice.ts
  src/slices/reducer.ts
  src/slices/user/actions.ts
  src/slices/user/userSlice.ts
  src/state/store.ts
Labels: ⚙ Settings

#40 [Refactor] 회원가입 페이지, 로그인 페이지를 묶는 디렉토리 생성 및 파일 구조 수정합니다
  src/pages/Login/LogInForm.tsx
  src/pages/Login/index.tsx
  src/pages/index.ts
  src/pages/sign/Login/LogInForm.tsx
  src/pages/sign/Login/index.tsx
  src/pages/sign/SignUp/SignUpForm.tsx
  src/pages/sign/SignUp/index.tsx
  src/pages/sign/index.ts
  src/pages/user/index.ts
Labels: 🔨 Refactor

#41 [Settings] Lint 권한 설정 파일 업데이트 합니다
  .husky/commit-msg
  .husky/pre-commit
Labels: ⚙ Settings, 🐞 BugFix

#29 [Design] figma에 정의된 modal UI 구현
  src/assets/icons/check_circle.svg
  src/assets/icons/help.svg
  src/assets/icons/warning.svg
  src/components/Button/index.tsx
  src/components/modal/CoreModal/ErrorModal/index.tsx
  src/components/modal/CoreModal/QuestionModal/index.tsx
  src/components/modal/CoreModal/SuccessModal/index.tsx
  src/components/modal/CoreModal/index.tsx
  src/components/modal/index.ts
Labels: 🎨 Html&css

#36 [Feature] 메인 캘린더에 특정 월의 일자들이 요일에 맞춰 표시되도록 합니다
  src/pages/user/Schedule/ScheduleHeader/MonthPicker/index.tsx
  src/pages/user/Schedule/ScheduleHeader/MonthPickerDetail/index.tsx
  src/pages/user/Schedule/ScheduleHeader/constants.ts
  src/pages/user/Schedule/ScheduleHeader/index.tsx
  src/pages/user/Schedule/ScheduleMain/DaysOfWeek/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendar/MainCalendarDays/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendar/index.tsx
  src/pages/user/Schedule/ScheduleMain/index.tsx
  src/pages/user/Schedule/ScheduleSideBar/index.tsx
  src/pages/user/Schedule/core/TeamList/index.tsx
  src/pages/user/Schedule/index.tsx
Labels: ✨ Feature

#35 [Refactor] 구글 웹 폰트 아이콘을 이용하여 기존 아이콘 이미지 파일들을 대체합니다.
  index.html
  src/assets/icons/account_circle.png
  src/assets/icons/arrow_drop_down.png
  src/assets/icons/calendar_month.png
  src/assets/icons/check_box.png
  src/assets/icons/check_circle.svg
  src/assets/icons/help.svg
  src/assets/icons/home.png
  src/assets/icons/logout.png
  src/assets/icons/paid.png
  src/assets/icons/schedule.png
  src/assets/icons/supervisor_account.png
  src/assets/icons/warning.svg
  src/components/Layout/SideBar/Navigation/index.tsx
  src/components/Layout/SideBar/UserStatus/index.tsx
  src/pages/user/Schedule/ScheduleHeader/MonthPicker/index.tsx
  src/pages/user/Schedule/ScheduleHeader/index.tsx
Labels: 🔨 Refactor

#32 [Design/feature] figma에 정의된 pagination UI 구현
  src/components/PageNation/index.tsx
  src/components/Pagination/index.tsx
  src/routes/Router.tsx
  src/slices/pagination/action.ts
  src/slices/pagination/paginationSlice.ts
  src/slices/reducer.ts
  src/state/store.ts
Labels: ✨ Feature, 🎨 Html&css

#51 [Design] figma에 정의된 급여 정정 리스트 UI를 구현합니다
  src/components/Button/index.tsx
  src/components/Layout/SideBar/Navigation/index.tsx
  src/components/modal/payStub/AddPayStub/index.tsx
  src/components/modal/payStub/NomalPayStub/index.tsx
  src/pages/user/SalaryCorrection/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionHeader/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/index.tsx
  src/pages/user/SalaryCorrectionPage/index.tsx
  src/pages/user/SalaryDetails/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsHeader/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/index.tsx
  src/pages/user/SalaryDetailsPage/index.tsx
  src/pages/user/index.ts
Labels: 🎨 Html&css

#56 [Design] 피그마에 정의된 급여 내역 상세 UI를 구현
  src/components/modal/payStub/NormalPayStub/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionHeader/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/Header/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/AddPayStub/ModalBottom/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/AddPayStub/ModalHeader/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/AddPayStub/ModalMiddle/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/NormalPayStub/ModalBottom/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/NormalPayStub/ModalHeader/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/NormalPayStub/ModalMiddle/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/NormalPayStub/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/index.tsx
Labels: 🎨 Html&css

#59 [Feature/Design] 메인 캘린더에 데이터를 렌더링하고 상세 일정 페이지 화면을 구현합니다
  src/pages/user/Schedule/ScheduleHeader/index.tsx
  src/pages/user/Schedule/ScheduleMain/DetailScheduleWrapper/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendarWrapper/MainCalendar/MainCalendarDays/MainCalendarDaysSchedules/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendarWrapper/MainCalendar/MainCalendarDays/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendarWrapper/MainCalendar/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendarWrapper/index.tsx
  src/pages/user/Schedule/ScheduleMain/index.tsx
  src/pages/user/Schedule/ScheduleSideBar/index.tsx
  src/pages/user/Schedule/core/AddScheduleModal/AddScheduleModalContents/index.tsx
  src/pages/user/Schedule/core/AddScheduleModal/index.tsx
  src/pages/user/Schedule/core/TeamList/index.tsx
  src/pages/user/Schedule/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#66 [Feature] fetchDataFromDB 유틸 함수가 반환하는 값의 구조를 변경합니다
  src/firebase/fetchDataFromDB.ts
Labels: ✨ Feature

#67 [Design] 급여 정정 리스트 홈페이지 UI 구현
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyBottom/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyHeader/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyMiddle/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/Header/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/index.tsx
  src/pages/user/Schedule/ScheduleMain/DetailScheduleWrapper/index.tsx
  src/pages/user/Schedule/ScheduleMain/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#70 [Feature] 로그인과 회원가입 기능을 구현합니다
  public/avatar.svg
  src/components/form/Button/index.tsx
  src/components/form/ErrorMessage/index.tsx
  src/components/form/Input/index.tsx
  src/components/form/InputFile/index.tsx
  src/components/form/Textarea/index.tsx
  src/components/form/index.ts
  src/components/modal/CoreModal/SuccessModal/index.tsx
  src/constant/collection.ts
  src/constant/index.ts
  src/firebase/fetchUserInfo.tsx
  src/main.tsx
  src/pages/sign/Login/LogInForm.tsx
  src/pages/sign/Login/index.tsx
  src/pages/sign/SignUp/SignUpForm.tsx
  src/pages/user/Profile/ProfileForm.tsx
  src/styles/css/form.css
  src/styles/css/global.css
  src/styles/css/reset.css
  src/styles/css/token.css
  src/styles/index.css
  src/styles/index.ts
  src/styles/token/index.ts
  src/utils/format.ts
  src/utils/generate.ts
  src/utils/index.ts
Labels: ✨ Feature

#74 [Hotfix] Button 컴포넌트를 form 디렉토리 하위로 이동하여 생긴 import 경로 이슈를 해결합니다
  src/components/form/index.ts
  src/components/index.ts
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionHeader/index.tsx
  src/pages/user/Schedule/ScheduleHeader/index.tsx
Labels: 🔨 Refactor, 🐞 BugFix

#76 [Design/feature] 급여 정정 리스트 홈페이지 모달 구현
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionHeader/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyBottom/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyHeader/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyMiddle/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/AddPayStub/ModalBottom/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/AddPayStub/ModalHeader/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/AddPayStub/ModalMiddle/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/AddPayStub/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/AddPayStub/ModalHeader/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/AddPayStub/ModalMiddle/index.tsx
  src/types/interface.ts
Labels: ✨ Feature, 🎨 Html&css

#78 [Refactor] 급여 정정 신청시 데이터 구조 일치
  src/components/modal/CoreModal/ErrorModal/index.tsx
  src/components/modal/CoreModal/QuestionModal/index.tsx
  src/components/modal/CoreModal/SuccessModal/index.tsx
  src/components/modal/CoreModal/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyBottom/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyMiddle/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/AddPayStub/ModalMiddle/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/index.tsx
Labels: 🔨 Refactor

#79 [Feature] Firebase Storage에 파일을 업로드 및 삭제할 수 있는 컴포넌트를 구현합니다
  src/components/FileUploading/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/index.tsx
  src/pages/user/Schedule/ScheduleHeader/index.tsx
Labels: ✨ Feature

#81 [Feature] 버튼 컴포넌트를 구현합니다
  src/components/form/Button/index.tsx
  src/components/form/index.ts
Labels: 🔨 Refactor, 🎨 Html&css

#83 [Feature] 입력폼 유효성 검사와 로그인과 회원가입의 디자인 UI를 완성합니다
  src/assets/pokemonBall.svg
  src/components/IntroLayout/IntroSideVisual/index.tsx
  src/components/IntroLayout/index.tsx
  src/components/PageContainer/index.tsx
  src/components/PageTitle/index.tsx
  src/components/Title/index.tsx
  src/components/form/ErrorMessage/index.tsx
  src/components/form/Form/index.tsx
  src/components/form/Input/index.tsx
  src/components/form/LinkText/index.tsx
  src/components/form/index.ts
  src/components/index.ts
  src/constant/index.ts
  src/constant/regExp.ts
  src/pages/sign/Login/LogInForm.tsx
  src/pages/sign/Login/index.tsx
  src/pages/sign/SignUp/SignUpForm.tsx
  src/pages/sign/SignUp/index.tsx
  src/styles/css/form.css
  src/styles/css/reset.css
  src/styles/token/colors.ts
  src/styles/token/font.ts
  tsconfig.app.json
  tsconfig.json
Labels: ✨ Feature, 🎨 Html&css

#87 [Refactor: 급여 리스트 상세 모달 데이터 불러오기
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/NormalPayStub/ModalBottom/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/NormalPayStub/ModalHeader/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/NormalPayStub/ModalMiddle/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/NormalPayStub/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/index.tsx
Labels: 🔨 Refactor, 🎨 Html&css

#88 [Feature] 로그인 후 전역상태 관리와 인증 인가 처리를 합니다
  src/App.tsx
  src/components/Layout/SideBar/UserStatus/LoggoutButton/index.tsx
  src/components/Layout/SideBar/UserStatus/index.tsx
  src/components/UserProfilePhoto/index.tsx
  src/components/index.ts
  src/pages/sign/Login/LogInForm.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/Router.tsx
  src/slices/user/userSlice.ts
  src/state/store.ts
  src/styles/token/border.ts
  src/styles/token/colors.ts
Labels: ✨ Feature, 🔨 Refactor

#96 [Bugfix] 급여 정정 신청시 데이터 중복 저장 오류 해결
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyBottom/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyMiddle/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/AddPayStub/ModalMiddle/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/index.tsx
Labels: 🐞 BugFix

#97 [Feature/Design] 스케줄 페이지의 디자인과 추가 기능을 구현합니다
  src/components/FileUploading/index.tsx
  src/pages/user/Schedule/ScheduleMain/DetailScheduleWrapper/index.tsx
  src/pages/user/Schedule/core/ScheduleModal/ScheduleModalContents/index.tsx
  src/pages/user/Schedule/core/ScheduleModal/index.tsx
  src/pages/user/Schedule/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#98 [Design] 전체 공통 레이아웃의 디자인과 UX를 깔끔하게 정리합니다
  index.html
  src/components/IntroLayout/PageContainer/index.tsx
  src/components/IntroLayout/PageTitle/index.tsx
  src/components/Layout/Header/index.tsx
  src/components/Layout/Nav/index.tsx
  src/components/Layout/SideBar/BrandLogo/index.tsx
  src/components/Layout/SideBar/Navigation/constant.ts
  src/components/Layout/SideBar/Navigation/index.tsx
  src/components/Layout/SideBar/Navigation/style.ts
  src/components/Layout/SideBar/Navigation/type.ts
  src/components/Layout/SideBar/UserStatus/index.tsx
  src/components/Layout/SideBar/index.tsx
  src/components/Layout/index.tsx
  src/components/Loading/index.tsx
  src/components/Notice/index.tsx
  src/components/UserProfilePhoto/index.tsx
  src/components/index.ts
  src/constant/index.ts
  src/constant/url.ts
  src/pages/admin/EmployeeList/index.tsx
  src/pages/admin/SalaryRequest/index.tsx
  src/pages/sign/Login/LogInForm.tsx
  src/pages/sign/SignUp/SignUpForm.tsx
  src/pages/user/Attendance/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionHeader/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyMiddle/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/index.tsx
  src/pages/user/SalaryCorrectionPage/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsHeader/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/index.tsx
  src/pages/user/SalaryDetailsPage/index.tsx
  src/pages/user/UserHome/index.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/Router.tsx
  src/slices/user/userSlice.ts
  src/styles/token/font.ts
  src/styles/token/padding.ts
  src/utils/index.ts
  src/utils/navigate.ts
Labels: 🔨 Refactor, 🎨 Html&css

#99 [Docs] readme update
  README.md
Labels: 📃 Docs

#103 [Hotfix] merge 이후 로딩 변수 오탈자로 나타나는 렌더링 이슈 해결
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/index.tsx
  src/slices/navigation/actions.ts
  src/slices/navigation/navigationSlice.ts
  src/slices/reducer.ts
  src/state/store.ts
Labels: 🐞 BugFix

#101 [Feature/Refactor] 전역 상태를 활용하여 스케줄 페이지의 코드와 로직을 개선합니다
  src/constant/schedule.ts
  src/pages/user/Schedule/ScheduleHeader/MonthPicker/MonthPickerDetail/index.tsx
  src/pages/user/Schedule/ScheduleHeader/MonthPicker/index.tsx
  src/pages/user/Schedule/ScheduleHeader/index.tsx
  src/pages/user/Schedule/ScheduleMain/DetailScheduleWrapper/DetailSchedule/index.tsx
  src/pages/user/Schedule/ScheduleMain/DetailScheduleWrapper/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendar/MainCalendarDays/MainCalendarDaysSchedules/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendar/MainCalendarDays/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendar/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendarWrapper/MainCalendar/index.tsx
  src/pages/user/Schedule/ScheduleMain/MainCalendarWrapper/index.tsx
  src/pages/user/Schedule/ScheduleMain/index.tsx
  src/pages/user/Schedule/ScheduleSideBar/index.tsx
  src/pages/user/Schedule/constants.ts
  src/pages/user/Schedule/core/ScheduleModal/ScheduleModalContents/index.tsx
  src/pages/user/Schedule/core/ScheduleModal/index.tsx
  src/pages/user/Schedule/core/TeamList/index.tsx
  src/pages/user/Schedule/index.tsx
  src/slices/reducer.ts
  src/slices/schedule/actions.ts
  src/slices/schedule/scheduleSlice.ts
  src/state/store.ts
  src/types/schedule.ts
Labels: ✨ Feature, 🔨 Refactor

#105 [fix] 데이터를 저장하는 saveDataToDB 함수 내 유저 인증 검증 로직을 필수로 실행합니다.
  src/firebase/saveDataToDB.ts
  src/hooks/useSaveData.ts
  src/pages/user/Profile/ProfileForm.tsx
Labels: ✨ Feature

#109 [Refactor] useFetchUserInfo 대신 전역 상태 user를 사용
  src/components/Pagination/index.tsx
  src/constant/index.ts
  src/constant/pagination.ts
  src/pages/sign/LoginPage/LogInForm.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/AddPayStub/ModalHeader/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/NormalPayStub/ModalHeader/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/index.tsx
  src/slices/user/userSlice.ts
Labels: 🔨 Refactor

#113 [Design] 디자인 토큰 값 수정과 기본 UI 컴포넌트 스타일을 수정합니다
  src/components/Loading/index.tsx
  src/components/Pagination/index.tsx
  src/components/form/Input/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyHeader/index.tsx
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionApply/ApplyMiddle/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/NormalPayStub/ModalBottom/index.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsMain/NormalPayStub/ModalMiddle/index.tsx
  src/styles/token/border.ts
  src/styles/token/colorRawValue.ts
  src/styles/token/colors.ts
Labels: 🎨 Html&css

#118 [Design] 디자인 토큰의 light 색과 dark 색을 재정의 하고 전역 css를 동적으로 관리합니다
  src/App.tsx
  src/GlobalStyle.ts
  src/styles/css/form.css
  src/styles/css/global.css
  src/styles/css/token.css
  src/styles/index.css
  src/styles/token/colorRawValue.ts
  src/styles/token/colors.ts
Labels: 🔨 Refactor, 🎨 Html&css

#119 [Design] 뱃지 컴포넌트를 구현합니다
  src/components/Badge.tsx
Labels: 🎨 Html&css

#125 [ Fix] 네비게이션 활성화 이슈 수정 제거를 위한 리팩토링과 사이드바의 디자인을 디벨롭 합니다
  src/components/Icon.tsx
  src/components/Layout/BrandLogo.tsx
  src/components/Layout/NavText.tsx
  src/components/Layout/Navigation.tsx
  src/components/Layout/SideBar.tsx
  src/components/Layout/SideBar/Navigation/constant.ts
  src/components/Layout/SideBar/Navigation/index.tsx
  src/components/Layout/SideBar/Navigation/style.ts
  src/components/Layout/SideBar/Navigation/type.ts
  src/components/Layout/SideBar/UserStatus/LoggoutButton/index.tsx
  src/components/Layout/SideBar/UserStatus/index.tsx
  src/components/Layout/UserStatus.tsx
  src/components/Loading.tsx
  src/components/UserProfilePhoto.tsx
  src/components/index.ts
  src/components/modal/ClassicModal.tsx
  src/constant/index.ts
  src/constant/navigation.ts
  src/constant/url.ts
  src/hooks/index.ts
  src/hooks/useLogout.ts
  src/routes/Router.tsx
  src/styles/token/colors.ts
  src/types/index.ts
  src/types/navigation.ts
  src/utils/index.ts
  src/utils/navigate.ts
  src/utils/styleUtil.ts
Labels: 🔨 Refactor, 🐞 BugFix, 🎨 Html&css

#124 [Refactor/Bugfix] Pagination custom hook 제작
  src/components/Pagination.tsx
  src/hooks/usePagination.ts
  src/pages/user/SalaryCorrectionPage/SalaryCorrectionMain/SalaryCorrectionList.tsx
  src/pages/user/SalaryDetailsPage/SalaryDetailsPage.tsx
Labels: 🔨 Refactor, 🐞 BugFix
